project_id = "cqxcztafhnwkhxgaylne"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.contact-lead]
    verify_jwt = false
  [functions.translate]
    verify_jwt = false
  [functions.followup-lead]
    verify_jwt = false
